<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>nl.dotjava.javafx</groupId>
    <artifactId>nop</artifactId>
    <version>0.2</version>
    <name>Nop</name>

    <properties>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>

        <android.minSdkVersion>35</android.minSdkVersion>
        <android.targetSdkVersion>36</android.targetSdkVersion>
        <android.compileSdkVersion>36</android.compileSdkVersion>
        <android.buildToolsVersion>35.0.0</android.buildToolsVersion>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <org.openjfx.controls.version>17.0.17</org.openjfx.controls.version>
        <org.openjfx.fxml.version>17.0.17</org.openjfx.fxml.version>
        <org.controlsfx.controlsfx.version>11.2.2</org.controlsfx.controlsfx.version>

        <charm.glisten.version>6.2.3</charm.glisten.version>
        <gluonhq.attach.util.version>4.0.24</gluonhq.attach.util.version>
        <gluonhq.attach.lifecycle.version>4.0.24</gluonhq.attach.lifecycle.version>
        <gluonhq.attach.display.version>4.0.24</gluonhq.attach.display.version>
        <gluonhq.attach.storage.version>4.0.24</gluonhq.attach.storage.version>
        <gluonhq.attach.statusbar.version>4.0.24</gluonhq.attach.statusbar.version>

        <org.junit.jupiter.version>6.0.2</org.junit.jupiter.version>
        <org.assertj.version>3.27.7</org.assertj.version>

        <maven.compiler.plugin.version>3.14.0</maven.compiler.plugin.version>
        <javafx.maven.plugin.version>0.0.8</javafx.maven.plugin.version>
        <gluonfx.maven.plugin.version>1.0.28</gluonfx.maven.plugin.version>

        <main.class>nl.dotjava.javafx.nop.NopApplication</main.class>
    </properties>

    <dependencies>
        <!-- JavaFX -->
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${org.openjfx.controls.version}</version>
        </dependency>
        <!-- GluonHQ -->
        <dependency>
            <groupId>com.gluonhq</groupId>
            <artifactId>charm-glisten</artifactId>
            <version>${charm.glisten.version}</version>
        </dependency>
        <dependency>
            <groupId>com.gluonhq.attach</groupId>
            <artifactId>util</artifactId>
            <version>${gluonhq.attach.util.version}</version>
        </dependency>
        <dependency>
            <groupId>com.gluonhq.attach</groupId>
            <artifactId>lifecycle</artifactId>
            <version>${gluonhq.attach.lifecycle.version}</version>
        </dependency>
        <dependency>
            <groupId>com.gluonhq.attach</groupId>
            <artifactId>display</artifactId>
            <version>${gluonhq.attach.display.version}</version>
        </dependency>
        <dependency>
            <groupId>com.gluonhq.attach</groupId>
            <artifactId>storage</artifactId>
            <version>${gluonhq.attach.storage.version}</version>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${org.junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${org.junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${org.assertj.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>android</id>
            <properties>
                <gluonfx.target>android</gluonfx.target>
                <packageName>nl.dotjava.javafx.nop</packageName>
                <manifestPath>${project.basedir}/android/AndroidManifest.xml</manifestPath>
                <compileSdkVersion>${android.compileSdkVersion}</compileSdkVersion>
                <minSdkVersion>${android.minSdkVersion}</minSdkVersion>
                <targetSdkVersion>${android.targetSdkVersion}</targetSdkVersion>
                <buildToolsVersion>${android.buildToolsVersion}</buildToolsVersion>
            </properties>
        </profile>
        <profile>
            <id>ios</id>
            <properties>
                <gluonfx.target>ios</gluonfx.target>
            </properties>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <release>17</release>
                </configuration>
            </plugin>
            <!-- gluonfx maven plugin to build native android or ios package -->
            <plugin>
                <groupId>com.gluonhq</groupId>
                <artifactId>gluonfx-maven-plugin</artifactId>
                <version>${gluonfx.maven.plugin.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <verbose>true</verbose>
                    <target>${gluonfx.target}</target>
                    <!-- <android> -->
                    <!--     <packageName>nl.dotjava.javafx.nop</packageName>    -->
                    <!-- </android> -->
                    <nativeImageArgs>
                        <arg>-J-Xmx8g</arg>
                        <arg>--allow-incomplete-classpath</arg>
                        <!-- <arg>-H:CompilerBackend=llvm</arg>                       -->
                        <!-- <arg>-H:CompilerPath=aarch64-linux-android30-clang</arg> -->
                        <!-- <arg>-H:-CheckToolchain</arg>                            -->
                        <!-- <arg>-H:-UseCAPCache</arg>                               -->
                        <!-- <arg>-H:-NewCAPCache</arg>                               -->
                        <!-- <arg>-H:-CheckToolchain</arg>                            -->
                    </nativeImageArgs>
                    <attachList>
                        <list>util</list>
                        <list>lifecycle</list>
                        <list>display</list>
                        <list>storage</list>
                        <!-- <list>statusbar</list> -->
                    </attachList>
                    <jniList>com.gluonhq.attach.util.impl.AndroidUtil</jniList>
                    <reflectionList>
                        <list>com.gluonhq.attach.util.Services</list>
                        <!-- needed? -->
                        <!-- <list>com.gluonhq.attach.display.impl.DisplayServiceFactory</list> -->
                    </reflectionList>
                    <mainClass>${main.class}</mainClass>
                    <!-- added for Google Play Console -->
                    <releaseConfiguration>
                        <appLabel>Nop</appLabel>
                        <versionCode>1</versionCode>
                        <versionName>1.2</versionName>
                    </releaseConfiguration>
                </configuration>
            </plugin>
            <!-- javafx maven plugin for local deployment -->
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>${javafx.maven.plugin.version}</version>
                <executions>
                    <execution>
                        <id>default-cli</id>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>${main.class}</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
