<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>nl.dotjava.javafx</groupId>
    <artifactId>nop</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>nop</name>

    <properties>
        <android.compileSdkVersion>33</android.compileSdkVersion>
        <android.minSdkVersion>26</android.minSdkVersion>
        <android.targetSdkVersion>33</android.targetSdkVersion>
        <android.buildToolsVersion>33.0.2</android.buildToolsVersion>

        <java.version>23</java.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <maven.compiler.release>21</maven.compiler.release>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <javafx.controls.version>17.0.6</javafx.controls.version>
        <javafx.fxml.version>17.0.6</javafx.fxml.version>
        <controlsfx.version>11.2.1</controlsfx.version>
        <substrate.version></substrate.version>
        <charm.glisten.version>6.2.3</charm.glisten.version>
        <attach.display.version>4.0.6</attach.display.version>
        <attach.util.version>4.0.6</attach.util.version>
        <bootstrapfx.core.version>0.4.0</bootstrapfx.core.version>
        <junit.version>5.10.2</junit.version>
        <maven.compiler.plugin.version>3.13.0</maven.compiler.plugin.version>
        <gluonfx.maven.plugin.version>1.0.25</gluonfx.maven.plugin.version>
        <javafx.maven.plugin.version>0.0.8</javafx.maven.plugin.version>

        <main.class>nl.dotjava.javafx.nop.NopApplication</main.class>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${javafx.controls.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${javafx.fxml.version}</version>
        </dependency>
        <dependency>
            <groupId>org.controlsfx</groupId>
            <artifactId>controlsfx</artifactId>
            <version>${controlsfx.version}</version>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>com.gluonhq</groupId>-->
<!--            <artifactId>substrate</artifactId>-->
<!--            <version>${substrate.version}</version>-->
<!--        </dependency>-->

        <dependency>
            <groupId>com.gluonhq</groupId>
            <artifactId>charm-glisten</artifactId>
            <version>${charm.glisten.version}</version>
        </dependency>
        <dependency>
            <groupId>com.gluonhq.attach</groupId>
            <artifactId>display</artifactId>
            <version>${attach.display.version}</version>
        </dependency>
        <dependency>
            <groupId>com.gluonhq.attach</groupId>
            <artifactId>util</artifactId>
            <version>${attach.util.version}</version>
        </dependency>
        <dependency>
            <groupId>org.kordamp.bootstrapfx</groupId>
            <artifactId>bootstrapfx-core</artifactId>
            <version>${bootstrapfx.core.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>android</id>
            <properties>
                <gluonfx.target>android</gluonfx.target>
                <packageName>nl.dotjava.javafx.nop</packageName>
                <manifestPath>${project.basedir}/android/AndroidManifest.xml</manifestPath>
                <compileSdkVersion>${android.compileSdkVersion}</compileSdkVersion>
                <minSdkVersion>${android.minSdkVersion}</minSdkVersion>
                <targetSdkVersion>${android.targetSdkVersion}</targetSdkVersion>
                <buildToolsVersion>${android.buildToolsVersion}</buildToolsVersion>
            </properties>
        </profile>
        <profile>
            <id>ios</id>
            <properties>
                <gluonfx.target>ios</gluonfx.target>
            </properties>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
            </plugin>
            <!-- GluonHQ maven plugin for mvn gluonfx:build gluonfx:package -Pandroid or -Pios -->
            <plugin>
                <groupId>com.gluonhq</groupId>
                <artifactId>gluonfx-maven-plugin</artifactId>
                <version>${gluonfx.maven.plugin.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <verbose>true</verbose>
                    <target>${gluonfx.target}</target>
<!--                    <android>-->
<!--                        <packageName>nl.dotjava.javafx.nop</packageName>-->
<!--                    </android>-->
                    <nativeImageArgs>
                        <arg>--allow-incomplete-classpath</arg>
<!--                        <arg>-H:CompilerBackend=llvm</arg>-->
<!--                        <arg>-H:CompilerPath=aarch64-linux-android30-clang</arg>-->
<!--                        <arg>-H:-CheckToolchain</arg>-->
<!--                        <arg>-H:-UseCAPCache</arg>-->
<!--                        <arg>-H:-NewCAPCache</arg>-->
<!--                        <arg>-H:-CheckToolchain</arg>-->
                    </nativeImageArgs>
                    <attachList>
                        <list>display</list>
                        <list>util</list>
                    </attachList>
                    <jniList>com.gluonhq.attach.util.impl.AndroidUtil</jniList>
                    <reflectionList>
                        <list>com.gluonhq.attach.util.Services</list>
                        <list>com.gluonhq.attach.display.impl.DisplayServiceFactory</list>
                    </reflectionList>
                    <mainClass>${main.class}</mainClass>
                </configuration>
            </plugin>
            <!-- JavaFX maven plugin for mvn javafx:run -->
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>${javafx.maven.plugin.version}</version>
                <executions>
                    <execution>
                        <id>default-cli</id>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>${main.class}</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
